# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jawaher_Lab1_Chat_App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jawaher_Lab1_Chat_App

pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'


end
